# -*- coding: utf-8 -*-
"""Weekly Project 1- Python Programming

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_r6AbLJ4L1n5iD5Ts-pxSlamcmI4tJfl
"""

import pandas as pd

produk = {
    'NVL': ('Novel', 25000.0),
    'KMK': ('Komik', 15000.0),
    'EPD': ('Ensiklopedia', 90000.0),
    'BIG': ('Biografi', 50000.0)
}

def menu():
    print('    TOKO BUKU MAKMUR JAYA')
    print('----------------------------------')
    print(f"{'Kode':<7}{'Kategori':<14}{'Harga':<15}")
    print('----------------------------------')
    for kode, (kategori, harga) in produk.items():
        print(f"{kode:<7}{kategori:<14}Rp. {harga:,.2f}")
    print('----------------------------------')

def input_transaksi():
    nama_pelanggan = input('Masukkan Nama Pembeli: ')
    garis()
    shopping_cart = []

    while True:
        print(f"{'Data ke-'}{len(shopping_cart) + 1}")
        print("Pilih opsi:")
        print("1. Tambah Item")
        print("2. Hapus Item")
        print("3. Reset Transaksi")
        print("4. Selesai Belanja")
        option = input("Masukkan opsi (1/2/3/4): ")

        if option == '1':
            tambah_item(shopping_cart)
        elif option == '2':
            hapus_item(shopping_cart)
        elif option == '3':
            shopping_cart = []  # Reset keranjang belanja
            print('Transaksi telah di-reset.')
        elif option == '4':
            break
        else:
            print('Opsi tidak valid. Silakan pilih opsi.')

        garis()
        print(f"{'Nama Pembeli:':<28}{nama_pelanggan}")
        garis()
        display_shopping_cart(shopping_cart)

    return nama_pelanggan, shopping_cart

def tambah_item(shopping_cart):
    menu()
    kode = input('Masukkan Kode Buku: ')
    if kode in produk:
        kategori, harga = produk[kode]
        while True:
            jumlah_beli = input('Masukkan Jumlah Beli: ')
            if jumlah_beli.isdigit():
                jumlah_beli = int(jumlah_beli)
                subtotal = harga * jumlah_beli
                shopping_cart.append([kode, kategori, harga, jumlah_beli, subtotal])
                break
            else:
                print('Jumlah beli harus angka.')
    else:
        print('Maaf, barang tidak tersedia')

def hapus_item(shopping_cart):
    kode_hapus = input('Masukkan Kode Barang yang akan dihapus: ')
    item_ditemukan = False
    for item in shopping_cart:
        if item[0] == kode_hapus:
            shopping_cart.remove(item)
            item_ditemukan = True
            print(f'Barang dengan kode {kode_hapus} telah dihapus dari keranjang belanja.')
            break
    if not item_ditemukan:
        print(f'Barang dengan kode {kode_hapus} tidak ditemukan dalam keranjang belanja.')

def garis():
    print('------------------------------------------')

def display_shopping_cart(shopping_cart):
    df = pd.DataFrame(shopping_cart, columns=['Kode', 'Kategori', 'Harga', 'Qty', 'Subtotal'])
    print(df.to_string(index=False))

def calculate_discount(total):
    return total * 0.1 if total >= 50000 else 0.0

def display_payment_summary(nama_pelanggan, shopping_cart):
    total_belanjaan = sum(item[4] for item in shopping_cart)
    discount = calculate_discount(total_belanjaan)
    total_setelah_diskon = total_belanjaan - discount

    garis()
    struk_title = '===== STRUK PEMBAYARAN ====='.center(40)
    print(struk_title)

    print('Nama Pembeli:', nama_pelanggan)
    display_shopping_cart(shopping_cart)
    garis()
    print(f"{'Total belanjaan':<25}Rp. {total_belanjaan:,.2f}")
    print(f"{'Diskon yang diberikan':<25}Rp. {discount:,.2f}")
    print(f"{'Total setelah diskon':<25}Rp. {total_setelah_diskon:,.2f}")

    while True:
        bayar = input('Masukkan uang bayar      Rp. ')
        if bayar.replace('.', '', 1).isdigit():
            bayar = float(bayar)
            break
        else:
            print('Uang bayar harus angka.')

    kembalian = bayar - total_setelah_diskon

    garis()

    struk_title = '===== STRUK PEMBAYARAN ====='.center(40)
    print(struk_title)

    print('Nama Pembeli:', nama_pelanggan)
    display_shopping_cart(shopping_cart)
    garis()
    print(f'{"Diskon yang diberikan":<25}Rp. {discount:,.2f}')
    print(f'{"Total setelah diskon":<25}Rp. {total_setelah_diskon:,.2f}')
    print(f'{"Uang bayar":<25}Rp. {bayar:,.2f}')
    print(f'{"Uang kembalian":<25}Rp. {kembalian:,.2f}')
    garis()

def main():
    while True:
        menu()
        nama_pelanggan, shopping_cart = input_transaksi()
        display_payment_summary(nama_pelanggan, shopping_cart)

        option = input('Lakukan transaksi lain? (Y/N): ').lower()
        if option != 'y':
            break

if __name__ == "__main__":
    main()